import numpy as np

raio_equatorial = 0
velocidade_inercial_de_rotação_da_terra = 0
mut = 0
J2 = 0
J3 = 0
J4 = 0
gravidade_padrao_nivel_do_mar = 0
lc = 0
dT = 0
area_de_referencia = np.zeros(4).T
fator_correcao_arrasto = 0
massa_estrutural_por_estagio = np.zeros(3)
m0 = np.zeros(3)
mp = np.zeros(4)
ti = np.zeros(4)
tq = np.zeros(4)
tempo_limite_separacao = np.zeros(3)
impulso_especifico_por_estagio = np.zeros(3)
Ts1 = 0
Ts2 = 0
Ts3 = 0
h0 = 0
comprimento_do_trilho = 0
tg = 0.0
agso = 0
Tq3 = 0
Tq31 = 0
Tq32 = 0
vgso = 0
mp3 = 0
Tq1 = 0
Tq2 = 0
massa_de_carga_util = 0
# ft = 0
# m = 0
sinalPhii = 0
achouApogeu = 0
mp31 = 0
mp32 = 0
DVgso = 0
